### ISSUE TITLE
restructure  recommendation  

### ISSUE THREAD

**Issue by khalidabuhayea** [AliAsadi/MovieCleanArchitecture#1]
I recommend to use this structure  and divide your project to modules instead of packages.
![Android-Clean-Architecture](https://user-images.githubusercontent.com/33156642/82142367-7ff23800-9844-11ea-9272-76c32bcde146.png)

**Comment by AliAsadi** [comment]
Dividing the project into modules actually is the best practice I keep it in packages for simplicity maybe will change that someday, for now, i wanna keep it simple as possible.

About the structure, I'm already using this one if you see any differentiation please provide more information.

**Comment by khalidabuhayea** [comment]
sorry Ali, this is structure what I meant : entities > domain > presentation.
presentation depend on domain and domain depend on entities.

![0_sfCDEb571WD-7EfP](https://user-images.githubusercontent.com/33156642/82143316-a9629200-984b-11ea-8fec-48f7d695485f.jpg)

**Comment by AliAsadi** [comment]
All is good but still, no differentiation bro in the project I have the same structure.

**Comment by AliAsadi** [comment]
@khalidabuhayea Update: The project is now using modules rather than packages 🙌🏼
